// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {config} from '../models';
import {grouping} from '../models';
import {uninstall} from '../models';
import {backup} from '../models';
import {maintenance} from '../models';
import {main} from '../models';

export function CancelClean():Promise<void>;

export function CancelMaintenance():Promise<void>;

export function CancelScan():Promise<void>;

export function CheckFDA():Promise<any>;

export function CleanOldBackups():Promise<number>;

export function CopyPath(arg1:string):Promise<void>;

export function DeleteBackup(arg1:string):Promise<void>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetCategories():Promise<Array<core.Category>>;

export function GetConfig():Promise<config.Config>;

export function GetHome():Promise<string>;

export function GetScanResult(arg1:string):Promise<core.ScanResult>;

export function GroupItems(arg1:string,arg2:Record<string, number>):Promise<Array<grouping.DisplayRow>>;

export function IsAppRunning(arg1:string):Promise<boolean>;

export function ListApps():Promise<Array<uninstall.AppInfo>>;

export function ListBackups():Promise<Array<backup.Info>>;

export function OpenFDASettings():Promise<void>;

export function RestoreBackup(arg1:string):Promise<backup.RestoreResult>;

export function RevealInFinder(arg1:string):Promise<void>;

export function RunMaintenance(arg1:string):Promise<maintenance.Result>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartClean(arg1:Record<string, Array<string>>,arg2:main.CleanOptions):Promise<void>;

export function StartScan(arg1:Array<string>):Promise<void>;

export function StartTMSnapshotsClear():Promise<void>;

export function StartUninstall(arg1:Array<string>,arg2:boolean):Promise<void>;
