// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelClean() {
  return window['go']['main']['App']['CancelClean']();
}

export function CancelMaintenance() {
  return window['go']['main']['App']['CancelMaintenance']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CheckFDA() {
  return window['go']['main']['App']['CheckFDA']();
}

export function CleanOldBackups() {
  return window['go']['main']['App']['CleanOldBackups']();
}

export function CopyPath(arg1) {
  return window['go']['main']['App']['CopyPath'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetScanResult(arg1) {
  return window['go']['main']['App']['GetScanResult'](arg1);
}

export function GroupItems(arg1, arg2) {
  return window['go']['main']['App']['GroupItems'](arg1, arg2);
}

export function IsAppRunning(arg1) {
  return window['go']['main']['App']['IsAppRunning'](arg1);
}

export function ListApps() {
  return window['go']['main']['App']['ListApps']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function OpenFDASettings() {
  return window['go']['main']['App']['OpenFDASettings']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function RunMaintenance(arg1) {
  return window['go']['main']['App']['RunMaintenance'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartClean(arg1, arg2) {
  return window['go']['main']['App']['StartClean'](arg1, arg2);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StartTMSnapshotsClear() {
  return window['go']['main']['App']['StartTMSnapshotsClear']();
}

export function StartUninstall(arg1, arg2) {
  return window['go']['main']['App']['StartUninstall'](arg1, arg2);
}
